sudo: required

# setting the language to bash speeds up builds compared to the default since there is no ruby installation
language: bash

cache:
  ccache: true
  directories:
    $HOME/.ci/boost

# Install latest Docker
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo cat /etc/docker/daemon.json
  # mirror.gcr.io in daemon.json doesn't work well with BuildKit
  - sudo rm -f /etc/docker/daemon.json
  - sudo systemctl restart docker

install:
  - scripts/docker-hub-login
  - scripts/fetch-buildpack
  - buildpack/scripts/build-deviceos
  - buildpack/scripts/build-image

script:
  - buildpack/scripts/run-tests-in-container
  - 'if [ -f /home/travis/build/.build/coverage.json ]; then python ci/report/report.py /home/travis/build/.build/coverage.json; rm -f /home/travis/build/.build/coverage.json; fi'

git:
  depth: 1

env:
  matrix:
  # Travis doesn't like to spin up more than 5 concurrent jobs at a time
    - BUILD_PLATFORM="photon p1 unit-test"
    - BUILD_PLATFORM="electron core gcc"
    - BUILD_PLATFORM="xenon asom newhal"
    - BUILD_PLATFORM="argon bsom"
    - BUILD_PLATFORM="boron xsom"

  global:
  - DOCKER_BUILDKIT=1
  - DOCKER_IMAGE_NAME=particle/buildpack-particle-firmware
  - secure: UM1+Ps1t21JfJaTFhuqkaY/U21j1Gfja6oSJTALcU0Y7zmo7TNyYMJwP+tbRfss7RBilWwUA8osr3sr6NXPREChojKpRQaRt52iD6wDfcxhsxGrpOU79cYO7FK1aQhCmhDGcnXahtxzbOGwS74jjTFW9U6TSveWa+EV1OgagLMc=
  - secure: aJ+EUGgXIp8t0s/f3EEyiUjYXnzAlYW9+jukG240A2Wb/XnGp9Av/JE+wBnBeMv7eF+hxkODo99gDXPumV6uYQevIBtqiHWtAu7kyvCxUWXhSmag+Q89pCJO8QpUrcxra9UZ6i+zhFEfskBctBjlT9nMKoUsGSg4jMg6Kx71QsA=
  - secure: Iq58mKqq5Nz4B6OEZu1nmnquhvlQncxT4T3f1x+M/0I6VW5xirMWFlpeke8QyyPOZlwNLDnB5QVjsR2UQspNIhMT4rCfDeCCr9AeinoMDmqPbzpmLLmtaUpz0uTZyJVx7+IRe9QtljPfbzlAxybmrx1HdCCw++F/+qhgFoGLi9o=
  - secure: O8Zu2sWO63svmSTdOk+7Z7N2oUcg3N07WckMoy1m7AYmRZydX5hdVXlbagA06FCtpu1Kvvwc7QYB+1wpoxZYZnxt2mVetVsAcSpOz3c03LodM+yKaHm9luqLfQobuC7oyNdumpqMLsWiELM9rxEpIazYDYM2QI+lh7fTUTHnQ3s=
  - secure: A83drTFobkGvgrPNwGwNS3ZSHX35iNELjH6W9h07pw/n1YSssBHxtLF8aVAEwfIF1VyUoHvQ4HYLNd+9RMyo162xxiWne+/4/gSFyUJNi11w3YX5bwodKPl7OwEO/YnJgHYk8YAAfdnZT4470Fpt6ytcOhEhMsB/IFeepMUiZZA=
notifications:
  slack:
    rooms:
      secure: Q+HuLmEeqSkRfiMYvqQpT7R6pfVghZ1OIXSm2hTAu3HVrMGBj6Jyp23k8EBnwjUnKxP/XZ88ARd3rOZF/vZF7wXixBhQtTdThUMUdKXAhvUkRHU0vmF7t+atsucwu1yp21jjWL7csnHmuH4qAoNdgLnoJYFImgRFoxB3weqVnEs=
